export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_USER: 'SET_USER',
    SET_ROUTE_NAME: 'SET_ROUTE_NAME'
};