export const dataArray2 = {
  '1': 'About',
  '2': 'AvailableOnPaidVersion',
  '3': 'AvailableOnPaidVersion',
  '4': 'BulletinQr',
  '5': 'AvailableOnPaidVersion',
  '6': 'ChildrenChurch',
  '7': 'Location',
  '8': 'Connect',
  '9': 'Contacts',
  '10': 'AvailableOnPaidVersion',
  '11': 'Events',
  '12': 'AvailableOnPaidVersion',
  '13': 'Help',
  '14': 'Homecell',
  '15': 'Grade Memory Verse',
  '16': 'NewMember',
  '17': 'AvailableOnPaidVersion',
  '18': 'AvailableOnPaidVersion',
  '19': 'Sermons',
  '20': 'AvailableOnPaidVersion',
  '21': 'AvailableOnPaidVersion',
  '22': 'AvailableOnPaidVersion',
  '23': 'Conversion',
  '24': 'AvailableOnPaidVersion',
  '25': 'NM-Resources',
  '26': 'AvailableOnPaidVersion',
};
