export const dataArray = [
  {id: '1', value: 'About Us'},
  {id: '2', value: 'Announcements'},
  {id: '3', value: 'Bible'},
  {id: '4', value: 'Bulletin'},
  {id: '5', value: 'Chats'},
  {id: '6', value: 'Children Church'},
  {id: '7', value: 'Church Location'},
  {id: '8', value: 'Connect'},
  {id: '9', value: 'Contacts'},
  {id: '10', value: 'Downloads'},
  {id: '11', value: 'Events'},
  {id: '12', value: 'Giving'},
  {id: '13', value: 'Help'},
  {id: '14', value: 'Home Cell'},
  {id: '15', value: 'Grade Memory Verse'},
  {id: '16', value: 'New Member Form'},
  {id: '17', value: 'Pastor Schedule'},
  {id: '18', value: 'Prayer Request'},
  {id: '19', value: 'Sermon'},
  {id: '20', value: 'Testimony'},
  {id: '21', value: 'Forum'},
  {id: '22', value: 'Projects'},
  {id: '23', value: 'Conversion'},
  {id: '24', value: 'Departments'},
  {id: '25', value: 'New Members Resources'},
  {id: '26', value: 'Notes'},
  {id: '27', value: 'Suggestion'},
  {id: '28', value: 'Online Conference'}
];
