export const dataArray2 = {
  '1': 'About',
  '2': 'SpecialAnnouncements',
  '3': 'BibleHome',
  '4': 'BulletinQr',
  '5': 'Chats',
  '6': 'ChildrenChurch',
  '7': 'Location',
  '8': 'Connect',
  '9': 'Contacts',
  '10': 'Downloads',
  '11': 'Events',
  '12': 'Giving',
  '13': 'Help',
  '14': 'Homecell',
  '15': 'Grade Memory Verse',
  '16': 'NewMember',
  '17': 'Bookappointment',
  '18': 'PrayerRequest',
  '19': 'Sermons',
  '20': 'TestimonyRoot',
  '21': 'Forum',
  '22': 'Projects',
  '23': 'Conversion',
  '24': 'Departments',
  '25': 'NM-Resources',
  '26': 'NoteRoot',
};
